actions:
  Add Account:
    action: account add
    alert: Please finish setup in browser and Voltron

tabular-data:
  accounts:
    title: Accounts
    identifier: id

    columns:
      - display_name
      - is_broadcaster
      - is_default
    column-detail:
      display_name:
        title: Display Name
      is_broadcaster:
        title: Is Broadcaster
        type: bool
      is_default:
        title: Is Default
        type: bool

    row-actions:
      - make_broadcaster
      - make_default
      - delete
    action-detail:
      make_broadcaster:
        title: Make Broadcaster
        action: account broadcaster {identifier}
        confirm: Are you sure you want to make {display_name} the broadcaster account?
      make_default:
        title: Make Default
        action: account default {identifier}
      delete:
        title: Delete Account
        action: account delete {identifier}
